//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salade
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    namespace Salade
    {
        public partial class Ingredient
        {
            public Ingredient()
            {
                this.Salades = new HashSet<Salade>();
            }
            [Key]
            public int Id { get; set; }

            [StringLength(50)]
            public string Nom { get; set; }
            public virtual ICollection<Salade> Salades { get; set; }
        }
    }
}
